name: Check pot

on: [push, pull_request]

jobs:
  checkPot:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Install dependencies
      run: pip install scons
    - name: Download tools
      run: |
        Invoke-WebRequest -Uri https://github.com/nvaccess/nvda-misc-deps/blob/fc1e9c47dc7f797fa0bca6cd91a32590fbf30edf/tools/msgfmt.exe -OutFile msgfmt.exe
        Invoke-WebRequest -Uri https://github.com/nvaccess/nvda-misc-deps/blob/fc1e9c47dc7f797fa0bca6cd91a32590fbf30edf/tools/xgettext.exe -OutFile ${{GITHUB_WORKSPACE}}\xgettext.exe

    - name: Build pot
      run: scons pot
      shell: cmd