name: Test title

on:
  pull_request:
    types:
      - edited

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const body = context.payload.pull_request.body
            if (body.includes('translation')) {
              const diff_url = context.payload.pull_request.diff_url
              const result = await github.request(diff_url)
              console.log(result.data)
            }
