name: Test title

on:
  pull_request:
    types:
      - labeled

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const opts = github.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            const labels = await github.paginate(opts)
            for (const label of labels) {
              if (label.name !== 'documentation') {
                continue
              }
              const diff_url = context.payload.pull_request.diff_url
              const result = await github.request(diff_url)
              console.log(result.data)
            }